
name: Exemplo Input
run-name: Exemplo workflow para input, executado por ${{ github.actor}}
on:
  workflow_dispatch:
    inputs:
      versao:
        type: string
        required: true
        default: "dev"
        description: "Versao da nova release"
      numero_card:
        type: number
        required: true
        description: "Numero do card da tarefa desse commit"
      fazer_deploy:
        type: boolean
        required: true
        description: "Específica se deve ou não fazer deploy"
      ambiente:
        type: choice
        required: true
        description: "ambiente de deploy"
        options:
          - dev
          - hml
          - prd
jobs:
  valores_input:
    runs_on: ubuntu_latest
    steps:
       - name: Exibindo o contexto de Input completo
       - run: echo "${{toJson(inputs)}}"
       - name: Exibindo valores individualmente
       - run: |
           echo "Esses são os valores fornecidos no input"
           echo: "A versão da app é: ${{ inputs.versao }}"
           acho: "O numero do card é: ${{ inputs.numero_card }}"
           echo: "Deve fazer deploy: ${{ inputs.fazer_deploy}}"
           echo: " Ambiente de deploy: ${{ inputs.ambiente}}"
        
      
          
