
name: Exemplo Input
run-name: Exemplo workflow para input, executado por ${{ github.actor}}
on:
  workflow_dispatch:
    inputs:
      versao:
        type: string
        required: true
        default: "dev"
        description: "Versao da nova release"
      numero_card:
        type: number
        required: true
        description: "Numero do card da tarefa desse commit"
      fazer_deploy:
        type: boolean
        required: true
        description: "Específica se deve ou não fazer deploy"
      ambiente:
        type: choice
        required: true
        description: "ambiente de deploy"
        options:
          - dev
          - hml
          - prd
jobs:
  valores_input:
    runs_on: ubuntu_latest
    steps:
       - name: Exibindo o contexto de Input completo
       - run: echo " echo ${{toJson(inputs)}}"
        
      
          
